version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.18.0
    - 4.19.0
    - 4.20.0
  - dependency-name: husky
    versions:
    - 5.1.3
    - 5.2.0
  - dependency-name: serverless-webpack
    versions:
    - 5.4.0
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: ini
    versions:
    - 1.3.7
